### ISSUE TITLE
Upload del file non funzionante!!

### ISSUE THREAD

**Issue by Andyrei** [LexyPie/laravel-form#1]
Secondo varie investigazioni e dopo l'installazione di Laravel su un server locale ho risconstrato errori! 

Quando faccio click su upload del file image mi manda sulla sulla pagina uploaded inserisce il tag img con il path nel src di "storage/images/nomeImg.jpg" ma non inserisce nulla nella cartella e, in più, la cartella non la crea nemmeno. 

Attendo la versione revisionata

**Comment by francesco-cadderi** [comment]
@Andyrei devi creare una connessione tra la cartella storage e quella public attraverso il comando:
php artisan storage:link

**Comment by Andyrei** [comment]
> @Andyrei devi creare una connessione tra la cartella storage e quella public attraverso il comando: php artisan storage:link

Ho provato ora funziona, è stato un errore mio. 

# Grazie :D
